llmmodels:
- name: ocsai-1.6
  description: Update to the multi-lingual, multi-task 1.5 model, trained on GPT 4o
    instead of 3.5.
  short-description: Multi-lingual, multi-task, gpt-4o-mini base
  format: ocsai2
  style: chat
  languages:
  - ara
  - chi
  - dut
  - eng
  - fre
  - ger
  - heb
  - ita
  - pol
  - rus
  - spa
  - CUSTOM
  tasks:
  - uses
  - completion
  - consequences
  - instances
  - metaphors
  - CUSTOM
  debug: true
  deprecated: false
  recommended: true
  production: true
- name: ocsai1-4o
  description: GPT-4o-based model, trained with more data and supporting multiple
    tasks. Last update to the Ocsai 1 models (i.e. the original ones).
  short-description: Ocsai 1, English-focused, gpt-4o-mini base
  format: classic_multi
  style: chat
  tasks:
  - uses
  - completion
  - consequences
  - instances
  debug: true
  deprecated: false
  recommended: true
  production: true
